### ISSUE TITLE
Undefined functions referred to by markdown-copy-paste-html

### ISSUE THREAD

**Issue by pierre-rouleau** [milkypostman/markdown-mode-plus#4]
* Problem 1: The  function `markdown-copy-html` was removed on [December 3, 2011 commit](https://github.com/milkypostman/markdown-mode-plus/commit/ad19b4d4027306ef20fa23bed8615f932991624b) yet it is still referred in the readme file and is called by the function `markdown-copy-paste-html`.
* Problem 2: The function `do-applescript` is also called by `markdown-copy-paste-html`.  It is not defined anywhere.  As far as I am concerned I wrote one such function with the same name and the same argument inside my [pel-applescript.el](https://github.com/pierre-rouleau/pel/blob/master/pel-applescript.el).  However no such function exists inside markdown-mode-plus.

**Comment by milkypostman** [comment]
It’s been a while since I needed these functions. I wonder if I just need to deprecate this package. 

Will take a look some evening.

**Comment by pierre-rouleau** [comment]
There are quite a bit of alternatives now and they all work on macOS, so it might be simpler for you to deprecate it.

**Comment by milkypostman** [comment]
Thanks @pierre-rouleau
